spring.application.name=servicio-cursos
server.port=${PORT:8081}


# Connection URL (default port is 5432)
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:scholar_system}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:10293}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

authentication.service.url=${AUTHENTICATION_SERVICE_URL:http://localhost:8080}

application.security.jwt.secret-key=claveSuperSecretaConDemaciadosCaracteresYalgunosNumerosComo12314143214

front.url=${FRONT_URL:http://localhost:5173}

spring.cloud.azure.storage.connection-string=${AZURE_CONNECTION_STRING}
spring.cloud.azure.storage.queue.queue-name=${AZURE_QUEUE_NAME}