spring.config.import=optional:file:.env[.properties]
spring.application.name=servicio-cursos
server.port=${PORT}
# Connection URL (default port is 5432)
# spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:scholar_system}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD}
# Hibernate properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
authentication.service.url=${AUTHENTICATION_SERVICE_URL}
application.security.jwt.secret-key=${JWT_SECRET_KEY}
front.url=${FRONT_URL}
spring.cloud.azure.storage.connection-string=${USERS_QUEUE_CONNECTION_STRING}
spring.cloud.azure.storage.queue.queue-name=${USERS_QUEUE_NAME}